version: '3.8'

services:
  scinote:
    build: .
    container_name: scinote-app
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scinote-network

  # 可选：添加Redis缓存服务
  # redis:
  #   image: redis:7-alpine
  #   container_name: scinote-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - scinote-network

networks:
  scinote-network:
    driver: bridge

volumes:
  # redis_data:
  #   driver: local
